services:
  task-db:
    image: task-db:latest
    container_name: task-db-container
    environment:
      POSTGRES_DB: taskdb
      POSTGRES_USER: taskuser
      POSTGRES_PASSWORD: taskpass
    build:
      context: ./02-multi-service-full-stack-app/Task-Manager-App/database
      dockerfile: Dockerfile
    volumes:
      - ./postgresql:/var/lib/postgresql    
    networks:
      - task-network
  task-app:
    image: task-app:latest
    container_name: task-app-container
    environment:
      DB_HOST: task-db\
      DB_NAME: taskdb
      DB_USER: taskuser
      DB_PASS: taskpass
    build:
      context: ./02-multi-service-full-stack-app/Task-Manager-App/frontend
      dockerfile: Dockerfile
    networks:
      - task-network
    ports:
      - "3000:3000"
    depends_on:
      - task-db
    restart: always

volumes:
  postgresql:

networks:
  task-network:

